apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paper-server
  namespace: argocd
spec:
  project: default
  source:
    # Replace <YOUR_GITHUB_USERNAME> with your GitHub username.
    repoURL: https://github.com/jacob/msud-cmute-gitops-workshop.git
    # Replace main with your branch if you made a specific branch
    # You will have to update the CI workflow to use the branch
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: paper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

